
services:
  # ============================================
  # BASE DE DATOS COMPARTIDA
  # ============================================
  postgres:
    image: postgres:15-alpine
    container_name: october_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: october_db
      POSTGRES_USER: october_user
      POSTGRES_PASSWORD: october_pass_2024
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - october_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U october_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ============================================
  # REDIS COMPARTIDO
  # ============================================
  redis:
    image: redis:7-alpine
    container_name: october_redis
    restart: unless-stopped
    volumes:
      - ./volumes/data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - october_network
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # ============================================
  # NGINX
  # ============================================
  nginx:
    image: nginx:alpine
    container_name: october_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/sites/v3.conf:/etc/nginx/conf.d/v3.conf:ro
      - ./config/nginx/sites/v4.conf:/etc/nginx/conf.d/v4.conf:ro
      - ./volumes/v3:/var/www/html:ro
      - ./volumes/v4:/var/www/html:ro
      - ./volumes/data/logs/nginx:/var/log/nginx
    networks:
      - october_network
    depends_on:
      - october-v3
      - october-v4

  # ============================================
  # OCTOBER CMS v3.7
  # ============================================
  october-v3:
    build:
      context: ./containers/october-v3
      dockerfile: Dockerfile
    container_name: october_v3
    restart: unless-stopped
    volumes:
      - ./volumes/v3:/var/www/html
      # PHP config is handled inside container
      # - ./config/php/v3-php.ini:/usr/local/etc/php/php.ini:ro
    environment:
      - OCTOBER_ENV=development
      - OCTOBER_VERSION=3.7
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=october_db
      - DB_USERNAME=october_user
      - DB_PASSWORD=october_pass_2024
      - DB_PREFIX=v3_
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DATABASE=0
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
    networks:
      - october_network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  # ============================================
  # OCTOBER CMS v4.0
  # ============================================
  october-v4:
    build:
      context: ./containers/october-v4
      dockerfile: Dockerfile
    container_name: october_v4
    restart: unless-stopped
    volumes:
      - ./volumes/v4:/var/www/html
      # PHP config is handled inside container
      # - ./config/php/v4-php.ini:/usr/local/etc/php/php.ini:ro
    environment:
      - OCTOBER_ENV=development
      - OCTOBER_VERSION=4.0
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=october_db
      - DB_USERNAME=october_user
      - DB_PASSWORD=october_pass_2024
      - DB_PREFIX=v4_
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DATABASE=1
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
    networks:
      - october_network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  # ============================================
  # HERRAMIENTAS DE DESARROLLO
  # ============================================
  mailhog:
    image: mailhog/mailhog:latest
    container_name: october_mailhog
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - october_network

  adminer:
    image: adminer:4.8.1
    container_name: october_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - october_network
    depends_on:
      - postgres

networks:
  october_network:
    name: october_network
    driver: bridge
volumes:
  postgres_data:
